# Generated by Django 2.0.5 on 2018-05-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(max_length=100)),
                ('data', models.DateTimeField(verbose_name='data opublikowania')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=50)),
                ('tresc', models.CharField(max_length=1000)),
                ('data', models.DateTimeField(verbose_name='data opublikowania')),
                ('haslo', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=20)),
                ('haslo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Uzytkownik'),
        ),
        migrations.AddField(
            model_name='komentarz',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Uzytkownik'),
        ),
    ]
