# Generated by Django 2.0.5 on 2018-06-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180528_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tresc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
