# Generated by Django 2.0.5 on 2018-06-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180603_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(default='', max_length=200)),
                ('obrazek', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
    ]
