# Generated by Django 2.0.5 on 2018-06-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180603_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='post',
            name='obrazek',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
