# Generated by Django 2.0.5 on 2018-06-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180603_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='obrazek',
            field=models.ImageField(upload_to='image'),
        ),
    ]
