# Generated by Django 2.0.5 on 2018-06-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180603_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='obrazek',
        ),
        migrations.AddField(
            model_name='post',
            name='obraz',
            field=models.ImageField(default='', upload_to='image'),
            preserve_default=False,
        ),
    ]
