# Generated by Django 2.0.5 on 2018-06-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180603_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obraz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazek', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='obraz',
        ),
    ]
