# Generated by Django 2.0.5 on 2018-06-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180603_2237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Obraz',
        ),
    ]
