# Generated by Django 2.0.5 on 2018-06-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_delete_obraz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='tresc',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
